/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutDemoStartServerFuncsRouteImport } from './routes/_layout/demo/start.server-funcs'
import { Route as LayoutDemoStartApiRequestRouteImport } from './routes/_layout/demo/start.api-request'
import { Route as LayoutDemoApiNamesRouteImport } from './routes/_layout/demo/api.names'
import { Route as LayoutDemoStartSsrIndexRouteImport } from './routes/_layout/demo/start.ssr.index'
import { Route as LayoutDemoStartSsrSpaModeRouteImport } from './routes/_layout/demo/start.ssr.spa-mode'
import { Route as LayoutDemoStartSsrFullSsrRouteImport } from './routes/_layout/demo/start.ssr.full-ssr'
import { Route as LayoutDemoStartSsrDataOnlyRouteImport } from './routes/_layout/demo/start.ssr.data-only'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDemoStartServerFuncsRoute =
  LayoutDemoStartServerFuncsRouteImport.update({
    id: '/demo/start/server-funcs',
    path: '/demo/start/server-funcs',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutDemoStartApiRequestRoute =
  LayoutDemoStartApiRequestRouteImport.update({
    id: '/demo/start/api-request',
    path: '/demo/start/api-request',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutDemoApiNamesRoute = LayoutDemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDemoStartSsrIndexRoute = LayoutDemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutDemoStartSsrSpaModeRoute =
  LayoutDemoStartSsrSpaModeRouteImport.update({
    id: '/demo/start/ssr/spa-mode',
    path: '/demo/start/ssr/spa-mode',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutDemoStartSsrFullSsrRoute =
  LayoutDemoStartSsrFullSsrRouteImport.update({
    id: '/demo/start/ssr/full-ssr',
    path: '/demo/start/ssr/full-ssr',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutDemoStartSsrDataOnlyRoute =
  LayoutDemoStartSsrDataOnlyRouteImport.update({
    id: '/demo/start/ssr/data-only',
    path: '/demo/start/ssr/data-only',
    getParentRoute: () => LayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/demo/api/names': typeof LayoutDemoApiNamesRoute
  '/demo/start/api-request': typeof LayoutDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof LayoutDemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof LayoutDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof LayoutDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof LayoutDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof LayoutDemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/demo/api/names': typeof LayoutDemoApiNamesRoute
  '/demo/start/api-request': typeof LayoutDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof LayoutDemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof LayoutDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof LayoutDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof LayoutDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof LayoutDemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/demo/api/names': typeof LayoutDemoApiNamesRoute
  '/_layout/demo/start/api-request': typeof LayoutDemoStartApiRequestRoute
  '/_layout/demo/start/server-funcs': typeof LayoutDemoStartServerFuncsRoute
  '/_layout/demo/start/ssr/data-only': typeof LayoutDemoStartSsrDataOnlyRoute
  '/_layout/demo/start/ssr/full-ssr': typeof LayoutDemoStartSsrFullSsrRoute
  '/_layout/demo/start/ssr/spa-mode': typeof LayoutDemoStartSsrSpaModeRoute
  '/_layout/demo/start/ssr/': typeof LayoutDemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/demo/api/names'
    | '/_layout/demo/start/api-request'
    | '/_layout/demo/start/server-funcs'
    | '/_layout/demo/start/ssr/data-only'
    | '/_layout/demo/start/ssr/full-ssr'
    | '/_layout/demo/start/ssr/spa-mode'
    | '/_layout/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/demo/start/server-funcs': {
      id: '/_layout/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof LayoutDemoStartServerFuncsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/demo/start/api-request': {
      id: '/_layout/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof LayoutDemoStartApiRequestRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/demo/api/names': {
      id: '/_layout/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof LayoutDemoApiNamesRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/demo/start/ssr/': {
      id: '/_layout/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof LayoutDemoStartSsrIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/demo/start/ssr/spa-mode': {
      id: '/_layout/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof LayoutDemoStartSsrSpaModeRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/demo/start/ssr/full-ssr': {
      id: '/_layout/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof LayoutDemoStartSsrFullSsrRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/demo/start/ssr/data-only': {
      id: '/_layout/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof LayoutDemoStartSsrDataOnlyRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDemoApiNamesRoute: typeof LayoutDemoApiNamesRoute
  LayoutDemoStartApiRequestRoute: typeof LayoutDemoStartApiRequestRoute
  LayoutDemoStartServerFuncsRoute: typeof LayoutDemoStartServerFuncsRoute
  LayoutDemoStartSsrDataOnlyRoute: typeof LayoutDemoStartSsrDataOnlyRoute
  LayoutDemoStartSsrFullSsrRoute: typeof LayoutDemoStartSsrFullSsrRoute
  LayoutDemoStartSsrSpaModeRoute: typeof LayoutDemoStartSsrSpaModeRoute
  LayoutDemoStartSsrIndexRoute: typeof LayoutDemoStartSsrIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDemoApiNamesRoute: LayoutDemoApiNamesRoute,
  LayoutDemoStartApiRequestRoute: LayoutDemoStartApiRequestRoute,
  LayoutDemoStartServerFuncsRoute: LayoutDemoStartServerFuncsRoute,
  LayoutDemoStartSsrDataOnlyRoute: LayoutDemoStartSsrDataOnlyRoute,
  LayoutDemoStartSsrFullSsrRoute: LayoutDemoStartSsrFullSsrRoute,
  LayoutDemoStartSsrSpaModeRoute: LayoutDemoStartSsrSpaModeRoute,
  LayoutDemoStartSsrIndexRoute: LayoutDemoStartSsrIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
